version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: series
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - postgres_pg

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8081:80
    depends_on:
      - postgres
    networks:
      - postgres_pg

networks:
  postgres_pg:
    driver: bridge